### ISSUE TITLE
Deployments failing due to missing zstd libraries in Remix server bundles

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#2588]
# Current behavior

Deployments are failing: https://github.com/nasa-gcn/gcn.nasa.gov/actions/runs/10925788532/job/30328269477

In  the CloudFormation console, I can see that the resource `AnyCatchallHTTPLambdaAliaslive` is failing to update with the following error message:

`Resource handler returned message: "Provisioned Concurrency configuration failed to be applied. Reason: FAILED" (RequestToken: ..., HandlerErrorCode: NotStabilized)`

This usually means that when AWS Lambda tries to start our code, it is crashing. Indeed, in the CloudWatch log, I see this exception:

```json
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '/_static/app/_assets/zstd.linux-arm64-gnu-4QNIIDDD.node'\nRequire stack:\n- /var/task/index.cjs\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '/_static/app/_assets/zstd.linux-arm64-gnu-4QNIIDDD.node'",
        "Require stack:",
        "- /var/task/index.cjs",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```

This broke due to #2568 which caused the Remix server code to depend up on gcn-kafka-js which in turn requires the zstd library. Native libraries are not bundled by default.

[Our build script for the custom Lambdas, `esbuild.js`](https://github.com/nasa-gcn/gcn.nasa.gov/blob/main/esbuild.js), contains a custom esbuild plugin to bundle them. I don't know at the moment if it is possible to customize Remix's build process in a similar manner.

Possible solutions:
- Ensure that it is always the table stream Lambda that is sending Kafka records.
- Extend the Remix build process to bundle native modules.

# Expected behavior

Lambda should start successfully.

# Steps to reproduce

N/A

# Environment

N/A
